name: "Teams Generator by Abdul Moiz Lakhani"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Intall Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build Angular App
        run: sudo npm run build

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy Angular App to Surge
        run: surge ./dist/teams-generator teams-generator-amlakhani.surge.sh --token ${{ secrets.SURGE_TOKEN }}